class BasePageLocators(object):
    input_field = './/input'

class DashboardLoginPageLocators(object):
    login_with_credentials_link = "//span[contains(text(),'Login with Pfizer credentials')]"
    Pfizer_NT_ID_INPUT="//input[@id='inputPfizerNetworkID']"
    Password_INPUT="//input[@id='inputPassword']"
    SUBMIT_BUTTON= "//button[contains(@class,'btn btn-primary')]"
    full_name_on_dashboard="//h1[contains(text()'Suresh Parimi')]"

class DashboardHomePageLocators(object):
    websites_menu_on_dashboard="//*[@id='block-ed-theme-mainnavigation']/ul/li[1]/a"
    offering_type="//a[contains(text(),'Edison Lite')]"
    websites_text = "//h1[contains(text(),'Websites')]"
    selected_offering_type_in_fliters = "//select[@id='edit-offering']//option[@selected]"
    URL = "https://smartsite-integration.pfizersite.io/"
    search_websites_input_field = "//input[@id='edit-keys--2']"
    auto_complete_field_url_in_search_websites="//div[@class='ui-autocomplete-field-prod_url']"
    auto_complete_field_name_in_search_websites="//div//span[@class='ui-autocomplete-field-term']"
    websites_menu_on_dashboard = "//ul[@class='menu nav navbar-nav']//li//a[contains(text(),'Websites')]"
    Tools_menu_on_dashboard = "//a[contains(text(),'Tools')]"
    
    

class DashBoardWebsitesPageLocators(object):
    sitename="//input[@id='edit-name']"
    audience="//select[@id='edit-field-site-metadata-audience-value']"
    offering="//select[@id='edit-offering']"
    usermanagement="//select[@id='edit-field-site-metadata-user-manager-value']"
    testsite="//select[@id='edit-test']"
    autologouttime="//select[@id='edit-field-site-metadata-autologout-value']"
    live="//select[@id='edit-live-timestamp']"
    internaldns="//select[@id='edit-field-site-metadata-internal-dns-value']"
    framework="//select[@id='edit-framework']"
    tags="//select[@id='edit-tags']"
    microservices="//select[@data-drupal-selector='edit-ms' and @id='edit-ms']"
    filter_button="//button[@id='edit-submit-smartsite-sites']"
    search_results_table_header_count="//table[@class='sticky-header table table-hover table-striped']//tr/th"
    all_websites_displayed_in_search_results= "//tbody/tr//td[1]//*[@href]"
    No_sites_available="//table[@class='table table-hover table-striped sticky-enabled sticky-table']//tr[@class='odd']"
    csv_export_button="//div[@class='csv-feed views-data-export-feed form-group']"
    add_site_button="//ul[@class='list-inline local-actions']"
    results_summary="//div[@class='result-summary']"

class HamburgerMenuLinksLocators(object):
    hamburger_icon="//section[@class='local-tasks__dropdown']/a"
    all_the_links_in_hamburger_menu="//ul[@class='tabs--primary nav nav-tabs']/li"
    prepare_mtp_link_in_hamburger_menu="//ul/li/a[contains(@href,'/mtp/add')]"
    view_link_in_hamburger_menu="//ul/li[@class='active']//span"
    edit_link_in_hamburger_menu="//ul/li/a[contains(@href,'/edit')]"
    delete_link_in_hamburger_menu="//ul/li/a[contains(@href,'/delete')]"
    platform_update_link_in_hamburger_menu="//ul/li/a[contains(@href,'/platform-update')]"
    ondemand_env_link_in_hamburger_menu="//ul/li/a[contains(@href,'/on-demand-env')]"
    
class AddSitePageLocators(object):
    add_site_header="//h1[contains(text()'Add site')]"
    sitename="//input[@id='edit-name-0-value']"
    offering="//select[@id='edit-site-type']"
    profile_stable_branch="//input[@id='edit-profile-stable-branch-0-value']"
    cloudflare_checkbox="//input[@id='edit-cloudflare-value']"
    cloudflare_access_checkbox="//input[@id='edit-cloudflare-access-value']"
    CI_builder="//select[@id='edit-smartsite-ci-plugin']"
    AWS_Hosting_checkbox="//input[@id='edit-aws-hosting-value']"
    live_checkbox="//input[@id='edit-live-value']"
    live_time_stamp_date_dropdown="//input[@id='edit-live-timestamp-0-value-date']"
    live_time_stamp_time_dropdown="//input[@id='edit-live-timestamp-0-value-time']"
    test_site_checkbox="//input[@id='edit-test-value']"
    state="//select[@id='edit-state']"
    site_enabled="//input[@id='edit-status-value']"
    authored_by="//input[@id='edit-user-id-0-target-id']"
    revision_log_message=""
    add_site_button=""
    save_button="//button[@id='edit-submit']"

class PrepareMTPpageLocators(object):
    prepare_mtp_page_title="//h1[contains(text()'Prepare MTP')]"
    all_options_in_mtp_type_dropdown="//select[@id='edit-type']"
    set_mtp_option = "//select[@id='edit-type']//option[@value=1]"
    mtp_date_widget="//input[@id='edit-date']"
    mtp_date_time_zone="//div[@id='edit_date_timezone_chosen']"
    mtp_date_time_zone_chosen_search_input = "//input[@class='chosen-search-input']"
    mtp_date_time_zone_chosen_result = "//ul[@class='chosen-results']//li"
    mtp_service_reqeust="//input[@id='edit-service-request']"
    mtp_solution_center_owner="//input[@id='edit-solution-center-owner']"
    mtp_vendor_assignee_field="//input[@id='edit-vendor-assignee']"
    mtp_manual_verification_input_field="//textarea[@id='edit-manual-verification-instructions']"
    mtp_submit_button="//button[@id='edit-submit']"
    mtp_cancel_button="//button[@id='edit-cancel']"
    mtp_when_and_how_to_use_this_field="//a[contains(text()'When and how to use this field.')]"
    error_message_on_prepare_mtp_form = "//div[@class='alert alert-danger alert-dismissible']//p"
    mtp_link_in_error_message = "//div[@class='alert alert-danger alert-dismissible']//p//a"



class MTPDetailsLocators(object):
    mtp_link_in_the_tools_menu = "//a[contains(text(),'MTPs')]"
    mtp_page_header = "//h1[contains(text(),'MTPs')]"
    sitename_in_mtp_page = "//input[@id='edit-site']"
    filter_button_in_mtp_page = "//button[@id='edit-submit-mtp']"
    cancel_mtp_link_hamburger_menu = "//a[contains(text(),'Cancel MTP')]"
    delete_mtp_link_hamburger_menu = "//a[contains(text(),'Delete')]"
    confirm_cancel_button = "//button[@id='edit-submit']"
    current_active_mtp_state = "//*[@id='pfizer-smartsite-server-mtp-progress-form']/ul/li[@class='active mtp-state-item']"
    list_of_all_mtp_statuses = "//*[@id='jpfizer-smartsite-server-mtp-progress-form']/ul/li[contains(@class,'mtp-state-item')]"
    mtp_sdlc_ticket_link = "//div[@id='edit-field-mtp-sdlc-doc']//a[@href]"
    jira_user_name = "//*[@id = 'username']"
    jira_password = "//*[@id='password']"
    jira_login_submit_button = "//button[@id = 'login-submit']"
    JIRA_SDLC_TICKET_INITIAL_STATUS = "//span[contains(text(),'In Draft')]"
    JIRA_SDLC_TICKET_select_Submit_Delverables_status = "//span[contains(text(),'Submit Deliverables')]"
    JIRA_SDLC_TICEKT_Submit_delivarables_Current_Status = "//span[contains(text(),'Deliverables Submitted')]"
    JIRA_SDLC_TICKET_select_Prelimanary_check_Passed_status = "//span[contains(text(),'Preliminary Check Passed')]"
    JIRA_SDLC_TICKET_select_SCO_APPROVED_status = "//span[contains(text(),'SCO Approved')]"
    JIRA_SDLC_TICEKT_SCO_APPROVED_Current_Status = "//span[contains(text(),'Approved (Pfizer Digital)')]"
    JIRA_SDLC_TICKET_select_READY_FOR_DEPLOYMENT_status = "//span[contains(text(),'Support Check Passed')]"
    JIRA_SDLC_TICKET_POP_UP_SUPPORT_CHECK_PASSED_BUTTON = "//input[@id='issue-workflow-transition-submit']"
    JIRA_SDLC_TICEKT_READY_FOR_DEPLOYMENT_Status = "//span[contains(text(),'Ready for Deployment')]"
    JIRA_SDLC_TICKET_FINAL_STATUS = "//span[contains(text(),'Approved (Pfizer Digital)')]"
    verify_dns_request_cutover_checkbox_unchecked = "//input[@name='field_mtp_dns_cutover']"
    verify_dns_request_cutover_checkbox_checked = "//input[@checked='checked' and @name='field_mtp_dns_cutover']"
    perform_MTP_button_in_ready_for_deployment_state = "//a[@id='edit-perform-mtp']"
    popup_dialog = "//div[@tabindex = '-1' and @role = 'dialog']"
    trigger_build_button_on_popup = "//button[@name='op' and @value = 'Trigger build']"


class changelogLocators(object):
    content_in_tool_bar = "//a[@id='toolbar-link-system-admin_content']"
    add_content_button = "//a[contains(text(),'Add content')]" 
    changerecod_link_in_add_content_page = "//span[contains(text(),'Change record')]"
    title_input_field = "//input[@id='edit-title-0-value']"
    all_options_in_chagerecord_type_dropdown = "//select[@id='edit-field-changelog-type']"
    event_date = "//input[@id='edit-field-event-date-0-value-date']"
    all_affects_check_boxes = "//input[contains(@data-drupal-selector,'edit-field-affected')]"
    all_affects_checkbox_descriptions = "//label[contains(text(),'-')]"
    summary_input_box = "//textarea[@id='edit-body-0-summary']"
    templates_icon_in_body_section = "//span[@class = 'cke_button_icon cke_button__templates_icon']"
    body_section_in_body = "//body[contains(@class,'cke')]"
    all_notifications_dropdown_values = "//select[contains(@id,'edit-simplenews-issue-target-id')]//option"
    all_contacts_in_contact_dropdown = "//select[contains(@id,'edit-field-contact')]//option"
    all_options_in_save_as_dropdown = "//select[contains(@id,'edit-moderation-state-0-state')]//option"
    revision_log_message_input_box = "//textarea[contains(@id,'edit-revision-log-0-value')]"
    save_button = "//input[@data-drupal-selector='edit-submit']"
    preview_button = "//input[@data-drupal-selector='edit-preview']"
